; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = example
default_envs = interactive

[env]
; board = seeed_xiao_esp32c3
; board = seeed_xiao_esp32s3
board = seeed_xiao_esp32c6
; board = m5stack-atoms3
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_src_flags =
	; -Weffc++
	; -Wformat=2 -Wconversion -Wtrampolines -Wimplicit-fallthrough -Wsuggest-override
lib_deps =
	symlink://.
	symlink://../libsesame3bt-core
build_src_filter =
build_flags =
	-Wall -Wextra
	-Ib:/.config/
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:arduino_2]
platform = espressif32 @ 6.10.0
build_flags =
	${env.build_flags}
	-DMBEDTLS_DEPRECATED_REMOVED=1
	-DCONFIG_BT_NIMBLE_ROLE_BROADCASTER_DISABLED=1
	-DCONFIG_BT_NIMBLE_ROLE_PERIPHERAL_DISABLED=1
	-DLIBSESAME3BT_DEBUG=1
	-DLIBSESAME3BTCORE_DEBUG=1
	-DCONFIG_NIMBLE_CPP_LOG_LEVEL=1
	-DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=6
	-DCONFIG_MBEDTLS_CMAC_C=1
	-std=gnu++17
build_unflags =
	${env.build_unflags}
	-std=gnu++11

[env:arduino_3]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.33/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-2/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip ; latest stable
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
build_flags =
	${env.build_flags}
	-DUSE_FRAMEWORK_MBEDTLS_CMAC
	-DLIBSESAME3BTCORE_DEBUG=1
	-DLIBSESAME3BT_DEBUG=1
custom_sdkconfig =
	CONFIG_BT_NIMBLE_MAX_CONNECTIONS=6
custom_component_remove =
    espressif/esp_hosted
    espressif/esp_wifi_remote
    espressif/esp-dsp
    espressif/esp32-camera
    espressif/libsodium
    espressif/esp-modbus
    espressif/qrcode
    espressif/esp_insights
    espressif/esp_diag_data_store
    espressif/esp_diagnostics
    espressif/esp_rainmaker
    espressif/rmaker_common

[env:interactive]
extends = env:arduino_3
build_src_filter = +<interactive/*> -<.git/> -<.svn/>

[env:by_address]
extends = env:arduino_3
build_src_filter = +<by_address/*> -<.git/> -<.svn/>

[env:by_address_multi]
extends = env:arduino_3
build_src_filter = +<by_address_multi/*> -<.git/> -<.svn/>

[env:by_scan]
extends = env:arduino_3
build_src_filter = +<by_scan/*> -<.git/> -<.svn/>

[env:repeat_scan]
extends = env:arduino_3
build_src_filter = +<repeat_scan/*> -<.git/> -<.svn/>

[env:test]
